create database capstone;
use capstone;

UPDATE staffs
SET manager_id = NULL
WHERE manager_id = 'NA';

-- Inner Join for Order Details o Join orders, order_items, and products to display detailed line items.
select o.order_id, o.order_date, oi.item_id, p.product_id, p.product_name, oi.quantity, oi.list_price, oi.discount, oi.total_price
from orders o
inner join order_items oi on oi.order_id = o.order_id
inner join products p on p.product_id = oi.product_id;


-- Write a query to group sales (total_price) by each store_id. 
select o.store_id, s.store_name, sum(oi.total_price) sales
from order_items oi
inner join orders o on o.order_id = oi.order_id
inner join stores s on s.store_id = o.store_id
group by o.store_id, s.store_name;


-- Top 5 Selling Products  o Use ORDER BY and LIMIT to get the top 5 most sold products by quantity. 
select product_name, sum(quantity) quantity
from order_items
group by product_name
order by quantity desc limit 5;


-- Customer Purchase Summary o For each customer, return total orders placed, total items purchased, and total revenue. 
select concat(c.first_name, ' ',c.last_name) customer_name, count(distinct o.order_id) total_orders, sum(oi.quantity) total_item_purchased, sum(oi.total_price) Total_revenue 
from order_items oi
inner join orders o on o.order_id = oi.order_id
inner join customers c on c.customer_id = o.customer_id
group by c.customer_id, c.first_name, c.last_name
order by total_revenue;


-- Segment Customers by Total Spend o Write a query to classify customers into spending brackets (e.g., low, medium, high).  
select c.customer_id, concat(c.first_name, ' ', c.last_name) customer_name, sum(oi.total_price) total_spending,
case
	when sum(oi.total_price) < 8000 then 'Low'
    when sum(oi.total_price) between 8000 and 15000 then 'Medium'
    else 'High'
end spending_segment
from customers c
inner join orders o on o.customer_id = c.customer_id
inner join order_items oi on oi.order_id = o.order_id
group by c.customer_id, c.first_name, c.last_name
order by sum(oi.total_price);


-- Staff Performance Analysis o Analyze total revenue generated by each staff member based on their handled orders.  
select s.staff_id, concat(s.first_name, ' ', s.last_name) staff_name, sum(oi.total_price) total_revenue, 
case
	when sum(oi.total_price) is null then 'No Sales'
	when sum(oi.total_price) < 100000 then 'Poor'
    when sum(oi.total_price) between 100000 and 1000000 then 'Average'
    else 'Good'
end staff_performance
from staffs s
left join orders o on o.staff_id = s.staff_id
left join order_items oi on oi.order_id = o.order_id
group by s.staff_id, s.first_name, s.last_name
order by sum(oi.total_price);


-- Stock Alert Query o Write a query to list products where stock quantity < 10 in any store. 
select st.store_id, st.store_name, p.product_id, p.product_name, s.quantity
from stores st
inner join stocks s on s.store_id = st.store_id
inner join products p on p.product_id = s.product_id
where s.quantity < 10
order by s.quantity;


-- Create Final Segmentation Table o Create a table customer_segments that will be populated from Python ML results later. 













